version: "3.8"

services:

  # Restaurant-service
  restaurant-service:
    build:
      context: ./backend/restaurant-service
    container_name: restaurant-service
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Restaurant
      - PORT=5002
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  # Order-service
  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Order
      - PORT=5005
    depends_on:
      - mongo

  # Auth-service
  auth-service:
    build:
      context: ./backend/auth-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Auth
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo

  # Payment-service
  payment-service:
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment
      - PORT=5004
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - mongo


  frontend:
    # Giả định cấu trúc Dockerfile nằm ở ./frontend/Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: frontend-app
    restart: unless-stopped
    # Ánh xạ ra cổng 3000 của host (hoặc cổng bạn muốn)
    ports:
      - "3000:3000" 
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_URL: http://auth-service:4000
      REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY}

  # MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

