version: "3.8"

services:

  # Restaurant-service
  restaurant-service:
    build:
      context: ./backend/restaurant-service
    container_name: restaurant-service
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Restaurant
      - PORT=5002
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - restaurant-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  # Order-service
  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Order
      - PORT=5005
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network

  # Auth-service
  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Auth
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1d
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - mongo
    networks:
      - app-network

  # Payment-service
  payment-service:
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment
      - PORT=5004
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://localhost:5001
        REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_51SU2MAKG4X6kws9TRlkXsZbacIvbuDikYxvtl6xCRNZoYvDJTCae91Mw8N7pq6avLmjYYSOXYMjfT426U61KXTJt00Ew95UeXa
        REACT_APP_ORDER_SERVICE_URL: http://localhost:5005
        REACT_APP_PAYMENT_SERVICE_URL: http://localhost:5004
        REACT_APP_AUTH_SERVICE_URL: http://localhost:5001
        REACT_APP_RESTAURANT_SERVICE_URL: http://localhost:5002
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - "3000:3000" 
    environment:
      REACT_APP_BACKEND_URL: http://auth-service:5001
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_51S6DRtPb5k3ojf4pY5t8beaMLClnsc0CwnowMxbCJW6henbjlN8uju2CVextQkMuncqKToNSZO18YdKXuOMTwQYl00Z6BWamZc
      REACT_APP_ORDER_SERVICE_URL: http://order-service:5005
      REACT_APP_PAYMENT_SERVICE_URL: http://payment-service:5004
      REACT_APP_AUTH_SERVICE_URL: http://auth-service:5001
      REACT_APP_RESTAURANT_SERVICE_URL: http://restaurant-service:5002
    depends_on:
      - auth-service
      - order-service
      - payment-service
      - restaurant-service
    networks:
      - app-network

  # MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  restaurant-uploads:
    driver: local