apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: foodfast
type: Opaque
stringData:
  # JWT Secret - THAY ĐỔI GIÁ TRỊ NÀY
  JWT_SECRET: "7f9c2a1b3e8d4f6c9a0b2e1d3c5f7a8b9c0d2e4f6a8b9c0d2e4f6a8b9c0d2e4f"
  
  # Stripe Configuration
  STRIPE_SECRET_KEY: "sk_test_51SU2MAKG4X6kws9TcA0sUZVS1B7hRNN0tmV0867l6b3OypghGeJ02xZbZjUfnXZJeyCvptped3FVBaxe29vgh7nk00pI8ddBLK"
  STRIPE_WEBHOOK_SECRET: "whsec_b5cb05273e19afc06d9c9250fab694ccef605cf02d69444b41569fec597016f8"
  REACT_APP_STRIPE_PUBLISHABLE_KEY: "pk_test_51SU2MAKG4X6kws9TRlkXsZbacIvbuDikYxvtl6xCRNZoYvDJTCae91Mw8N7pq6avLmjYYSOXYMjfT426U61KXTJt00Ew95UeXa"
  
  # Twilio Configuration - THAY ĐỔI GIÁ TRỊ NÀY
  TWILIO_ACCOUNT_SID: "ACe53519ca6b6025360d29b1c98b87a832"
  TWILIO_AUTH_TOKEN: "257f77560f3901d7c1dd3fbfe0d5cb91"
  TWILIO_PHONE_NUMBER: "+84764341662"
  
  # Resend API Key - THAY ĐỔI GIÁ TRỊ NÀY
  RESEND_API_KEY: "re_9uVeHAhj_2ytPCP3LVwjZiY5jUu9HvABN"