name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # B1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # B2 - Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # B3 - Build Docker image
      - name: Build Docker image
        run: |
          docker build -t masao1010/cnpm-doan-restaurant-service:latest ./backend/restaurant-service
          docker build -t masao1010/cnpm-doan-payment-service:latest ./backend/payment-service
          docker build -t masao1010/cnpm-doan-order-service:latest ./backend/order-service
          docker build -t masao1010/cnpm-doan-auth-service:latest ./backend/auth-service
          docker build -t masao1010/cnpm-doan-frontend:latest ./frontend

      # B4 - Push Docker image
      - name: Push Docker image
        run: |
          docker push masao1010/cnpm-doan-restaurant-service:latest
          docker push masao1010/cnpm-doan-payment-service:latest
          docker push masao1010/cnpm-doan-order-service:latest
          docker push masao1010/cnpm-doan-auth-service:latest 
          docker push masao1010/cnpm-doan-frontend:latest
